//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/cayley/graph/proto/primitive.proto
// Protobuf C++ Version: 6.33.4

#include "primitive.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {

inline constexpr Primitive::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{::uint64_t{0u}},
        subject_{::uint64_t{0u}},
        predicate_{::uint64_t{0u}},
        object_{::uint64_t{0u}},
        label_{::uint64_t{0u}},
        replaces_{::uint64_t{0u}},
        deleted_{false} {}

template <typename>
PROTOBUF_CONSTEXPR Primitive::Primitive(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Primitive_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PrimitiveDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PrimitiveDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PrimitiveDefaultTypeInternal() {}
  union {
    Primitive _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PrimitiveDefaultTypeInternal _Primitive_default_instance_;
}  // namespace proto
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto = nullptr;
const ::uint32_t
    TableStruct_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::Primitive, _impl_._has_bits_),
        11, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::Primitive, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::proto::Primitive, _impl_.subject_),
        PROTOBUF_FIELD_OFFSET(::proto::Primitive, _impl_.predicate_),
        PROTOBUF_FIELD_OFFSET(::proto::Primitive, _impl_.object_),
        PROTOBUF_FIELD_OFFSET(::proto::Primitive, _impl_.label_),
        PROTOBUF_FIELD_OFFSET(::proto::Primitive, _impl_.replaces_),
        PROTOBUF_FIELD_OFFSET(::proto::Primitive, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::proto::Primitive, _impl_.deleted_),
        1,
        2,
        3,
        4,
        5,
        6,
        0,
        7,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::Primitive)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::_Primitive_default_instance_._instance,
};
const char descriptor_table_protodef_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n>github.com/aperturerobotics/cayley/gra"
    "ph/proto/primitive.proto\022\005proto\"\214\001\n\tPrim"
    "itive\022\n\n\002ID\030\001 \001(\004\022\017\n\007Subject\030\002 \001(\004\022\021\n\tPr"
    "edicate\030\003 \001(\004\022\016\n\006Object\030\004 \001(\004\022\r\n\005Label\030\005"
    " \001(\004\022\020\n\010Replaces\030\006 \001(\004\022\r\n\005Value\030\010 \001(\014\022\017\n"
    "\007Deleted\030\t \001(\010*\203\001\n\rPrimitiveType\022\010\n\004LINK"
    "\020\000\022\007\n\003IRI\020\001\022\n\n\006STRING\020\002\022\t\n\005BNODE\020\003\022\r\n\tTY"
    "PED_STR\020\004\022\014\n\010LANG_STR\020\005\022\007\n\003INT\020\006\022\t\n\005FLOA"
    "T\020\007\022\010\n\004BOOL\020\010\022\r\n\tTIMESTAMP\020\tB0Z.github.c"
    "om/aperturerobotics/cayley/graph/protob\006"
    "proto3"
};
static ::absl::once_flag descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto = {
    false,
    false,
    406,
    descriptor_table_protodef_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto,
    "github.com/aperturerobotics/cayley/graph/proto/primitive.proto",
    &descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto::offsets,
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto,
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto,
};
namespace proto {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PrimitiveType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto);
  return file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PrimitiveType_internal_data_[] = {
    655360u, 0u, };
// ===================================================================

class Primitive::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Primitive>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Primitive, _impl_._has_bits_);
};

Primitive::Primitive(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Primitive_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.Primitive)
}
PROTOBUF_NDEBUG_INLINE Primitive::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::Primitive& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        value_(arena, from.value_) {}

Primitive::Primitive(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Primitive& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Primitive_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Primitive* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, deleted_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::deleted_));

  // @@protoc_insertion_point(copy_constructor:proto.Primitive)
}
PROTOBUF_NDEBUG_INLINE Primitive::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        value_(arena) {}

inline void Primitive::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, deleted_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::deleted_));
}
Primitive::~Primitive() {
  // @@protoc_insertion_point(destructor:proto.Primitive)
  SharedDtor(*this);
}
inline void Primitive::SharedDtor(MessageLite& self) {
  Primitive& this_ = static_cast<Primitive&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Primitive::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Primitive(arena);
}
constexpr auto Primitive::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Primitive),
                                            alignof(Primitive));
}
constexpr auto Primitive::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Primitive_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Primitive::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Primitive>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Primitive::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Primitive>(), &Primitive::ByteSizeLong,
              &Primitive::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Primitive, _impl_._cached_size_),
          false,
      },
      &Primitive::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Primitive_class_data_ =
        Primitive::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Primitive::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Primitive_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Primitive_class_data_.tc_table);
  return Primitive_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 8, 0, 0, 2>
Primitive::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Primitive, _impl_._has_bits_),
    0, // no _extensions_
    9, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966848,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Primitive_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::Primitive>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Primitive, _impl_.id_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(Primitive, _impl_.id_)}},
    // uint64 Subject = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Primitive, _impl_.subject_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(Primitive, _impl_.subject_)}},
    // uint64 Predicate = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Primitive, _impl_.predicate_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(Primitive, _impl_.predicate_)}},
    // uint64 Object = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Primitive, _impl_.object_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(Primitive, _impl_.object_)}},
    // uint64 Label = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Primitive, _impl_.label_), 5>(),
     {40, 5, 0,
      PROTOBUF_FIELD_OFFSET(Primitive, _impl_.label_)}},
    // uint64 Replaces = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Primitive, _impl_.replaces_), 6>(),
     {48, 6, 0,
      PROTOBUF_FIELD_OFFSET(Primitive, _impl_.replaces_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // bytes Value = 8;
    {::_pbi::TcParser::FastBS1,
     {66, 0, 0,
      PROTOBUF_FIELD_OFFSET(Primitive, _impl_.value_)}},
    // bool Deleted = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Primitive, _impl_.deleted_), 7>(),
     {72, 7, 0,
      PROTOBUF_FIELD_OFFSET(Primitive, _impl_.deleted_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 ID = 1;
    {PROTOBUF_FIELD_OFFSET(Primitive, _impl_.id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 Subject = 2;
    {PROTOBUF_FIELD_OFFSET(Primitive, _impl_.subject_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 Predicate = 3;
    {PROTOBUF_FIELD_OFFSET(Primitive, _impl_.predicate_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 Object = 4;
    {PROTOBUF_FIELD_OFFSET(Primitive, _impl_.object_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 Label = 5;
    {PROTOBUF_FIELD_OFFSET(Primitive, _impl_.label_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 Replaces = 6;
    {PROTOBUF_FIELD_OFFSET(Primitive, _impl_.replaces_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // bytes Value = 8;
    {PROTOBUF_FIELD_OFFSET(Primitive, _impl_.value_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bool Deleted = 9;
    {PROTOBUF_FIELD_OFFSET(Primitive, _impl_.deleted_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Primitive::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Primitive)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.value_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000feU)) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.deleted_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.deleted_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Primitive::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Primitive& this_ = static_cast<const Primitive&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Primitive::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Primitive& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.Primitive)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint64 ID = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_id(), target);
    }
  }

  // uint64 Subject = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_subject() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_subject(), target);
    }
  }

  // uint64 Predicate = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_predicate() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          3, this_._internal_predicate(), target);
    }
  }

  // uint64 Object = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_object() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          4, this_._internal_object(), target);
    }
  }

  // uint64 Label = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_label() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          5, this_._internal_label(), target);
    }
  }

  // uint64 Replaces = 6;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_replaces() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          6, this_._internal_replaces(), target);
    }
  }

  // bytes Value = 8;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_value().empty()) {
      const ::std::string& _s = this_._internal_value();
      target = stream->WriteBytesMaybeAliased(8, _s, target);
    }
  }

  // bool Deleted = 9;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_deleted() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          9, this_._internal_deleted(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.Primitive)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Primitive::ByteSizeLong(const MessageLite& base) {
  const Primitive& this_ = static_cast<const Primitive&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Primitive::ByteSizeLong() const {
  const Primitive& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.Primitive)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // bytes Value = 8;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_value().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_value());
      }
    }
    // uint64 ID = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_id());
      }
    }
    // uint64 Subject = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_subject() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_subject());
      }
    }
    // uint64 Predicate = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_predicate() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_predicate());
      }
    }
    // uint64 Object = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_object() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_object());
      }
    }
    // uint64 Label = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_label() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_label());
      }
    }
    // uint64 Replaces = 6;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_replaces() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_replaces());
      }
    }
    // bool Deleted = 9;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_deleted() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Primitive::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Primitive*>(&to_msg);
  auto& from = static_cast<const Primitive&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.Primitive)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_value().empty()) {
        _this->_internal_set_value(from._internal_value());
      } else {
        if (_this->_impl_.value_.IsDefault()) {
          _this->_internal_set_value("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_subject() != 0) {
        _this->_impl_.subject_ = from._impl_.subject_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_predicate() != 0) {
        _this->_impl_.predicate_ = from._impl_.predicate_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_object() != 0) {
        _this->_impl_.object_ = from._impl_.object_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_label() != 0) {
        _this->_impl_.label_ = from._impl_.label_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_replaces() != 0) {
        _this->_impl_.replaces_ = from._impl_.replaces_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_deleted() != 0) {
        _this->_impl_.deleted_ = from._impl_.deleted_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Primitive::CopyFrom(const Primitive& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.Primitive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Primitive::InternalSwap(Primitive* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Primitive, _impl_.deleted_)
      + sizeof(Primitive::_impl_.deleted_)
      - PROTOBUF_FIELD_OFFSET(Primitive, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata Primitive::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
