// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/cayleygraph/cayley/graph/proto/primitive.proto

package proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrimitiveType int32

const (
	PrimitiveType_LINK      PrimitiveType = 0
	PrimitiveType_IRI       PrimitiveType = 1
	PrimitiveType_STRING    PrimitiveType = 2
	PrimitiveType_BNODE     PrimitiveType = 3
	PrimitiveType_TYPED_STR PrimitiveType = 4
	PrimitiveType_LANG_STR  PrimitiveType = 5
	PrimitiveType_INT       PrimitiveType = 6
	PrimitiveType_FLOAT     PrimitiveType = 7
	PrimitiveType_BOOL      PrimitiveType = 8
	PrimitiveType_TIMESTAMP PrimitiveType = 9
)

var PrimitiveType_name = map[int32]string{
	0: "LINK",
	1: "IRI",
	2: "STRING",
	3: "BNODE",
	4: "TYPED_STR",
	5: "LANG_STR",
	6: "INT",
	7: "FLOAT",
	8: "BOOL",
	9: "TIMESTAMP",
}

var PrimitiveType_value = map[string]int32{
	"LINK":      0,
	"IRI":       1,
	"STRING":    2,
	"BNODE":     3,
	"TYPED_STR": 4,
	"LANG_STR":  5,
	"INT":       6,
	"FLOAT":     7,
	"BOOL":      8,
	"TIMESTAMP": 9,
}

func (x PrimitiveType) String() string {
	return proto.EnumName(PrimitiveType_name, int32(x))
}

func (PrimitiveType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1ce26ef49b449998, []int{0}
}

type Primitive struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Subject              uint64   `protobuf:"varint,2,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Predicate            uint64   `protobuf:"varint,3,opt,name=Predicate,proto3" json:"Predicate,omitempty"`
	Object               uint64   `protobuf:"varint,4,opt,name=Object,proto3" json:"Object,omitempty"`
	Label                uint64   `protobuf:"varint,5,opt,name=Label,proto3" json:"Label,omitempty"`
	Replaces             uint64   `protobuf:"varint,6,opt,name=Replaces,proto3" json:"Replaces,omitempty"`
	Timestamp            int64    `protobuf:"varint,7,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Value                []byte   `protobuf:"bytes,8,opt,name=Value,proto3" json:"Value,omitempty"`
	Deleted              bool     `protobuf:"varint,9,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Primitive) Reset()         { *m = Primitive{} }
func (m *Primitive) String() string { return proto.CompactTextString(m) }
func (*Primitive) ProtoMessage()    {}
func (*Primitive) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ce26ef49b449998, []int{0}
}

func (m *Primitive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Primitive.Unmarshal(m, b)
}
func (m *Primitive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Primitive.Marshal(b, m, deterministic)
}
func (m *Primitive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Primitive.Merge(m, src)
}
func (m *Primitive) XXX_Size() int {
	return xxx_messageInfo_Primitive.Size(m)
}
func (m *Primitive) XXX_DiscardUnknown() {
	xxx_messageInfo_Primitive.DiscardUnknown(m)
}

var xxx_messageInfo_Primitive proto.InternalMessageInfo

func (m *Primitive) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Primitive) GetSubject() uint64 {
	if m != nil {
		return m.Subject
	}
	return 0
}

func (m *Primitive) GetPredicate() uint64 {
	if m != nil {
		return m.Predicate
	}
	return 0
}

func (m *Primitive) GetObject() uint64 {
	if m != nil {
		return m.Object
	}
	return 0
}

func (m *Primitive) GetLabel() uint64 {
	if m != nil {
		return m.Label
	}
	return 0
}

func (m *Primitive) GetReplaces() uint64 {
	if m != nil {
		return m.Replaces
	}
	return 0
}

func (m *Primitive) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Primitive) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Primitive) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func init() {
	proto.RegisterEnum("proto.PrimitiveType", PrimitiveType_name, PrimitiveType_value)
	proto.RegisterType((*Primitive)(nil), "proto.Primitive")
}

func init() {
	proto.RegisterFile("github.com/cayleygraph/cayley/graph/proto/primitive.proto", fileDescriptor_1ce26ef49b449998)
}

var fileDescriptor_1ce26ef49b449998 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xcb, 0x4a, 0xc3, 0x40,
	0x14, 0x86, 0x9d, 0xdc, 0x73, 0x68, 0x65, 0x18, 0x44, 0x06, 0x71, 0x11, 0x5c, 0x05, 0x17, 0xed,
	0xc2, 0x95, 0xcb, 0x96, 0xd4, 0x12, 0x4c, 0x93, 0x32, 0x19, 0x04, 0x57, 0x92, 0xa4, 0x87, 0x36,
	0x92, 0xd0, 0xd0, 0xa6, 0x42, 0xd7, 0x3e, 0xae, 0x2f, 0x21, 0x99, 0xf4, 0xb2, 0x9a, 0xf9, 0xfe,
	0x9f, 0xef, 0xcc, 0x05, 0x5e, 0xd7, 0x65, 0xbb, 0x39, 0xe4, 0xa3, 0x62, 0x5b, 0x8f, 0x8b, 0xec,
	0x58, 0xe1, 0x71, 0xbd, 0xcb, 0x9a, 0xcd, 0x69, 0x3f, 0xee, 0xa1, 0xd9, 0x6d, 0xdb, 0xed, 0xb8,
	0xd9, 0x95, 0x75, 0xd9, 0x96, 0x3f, 0x38, 0x52, 0xcc, 0x4c, 0xb5, 0x3c, 0xfd, 0x11, 0x70, 0x97,
	0xe7, 0x8a, 0xdd, 0x82, 0x16, 0x06, 0x9c, 0x78, 0xc4, 0x37, 0x84, 0x16, 0x06, 0x8c, 0x83, 0x9d,
	0x1e, 0xf2, 0x6f, 0x2c, 0x5a, 0xae, 0xa9, 0xf0, 0x8c, 0xec, 0xb1, 0xd3, 0x70, 0x55, 0x16, 0x59,
	0x8b, 0x5c, 0x57, 0xdd, 0x35, 0x60, 0xf7, 0x60, 0x25, 0xbd, 0x66, 0xa8, 0xea, 0x44, 0xec, 0x0e,
	0xcc, 0x28, 0xcb, 0xb1, 0xe2, 0xa6, 0x8a, 0x7b, 0x60, 0x0f, 0xe0, 0x08, 0x6c, 0xaa, 0xac, 0xc0,
	0x3d, 0xb7, 0x54, 0x71, 0xe1, 0xee, 0x1c, 0x59, 0xd6, 0xb8, 0x6f, 0xb3, 0xba, 0xe1, 0xb6, 0x47,
	0x7c, 0x5d, 0x5c, 0x83, 0x6e, 0xde, 0x47, 0x56, 0x1d, 0x90, 0x3b, 0x1e, 0xf1, 0x07, 0xa2, 0x87,
	0xee, 0xd6, 0x01, 0x56, 0xd8, 0xe2, 0x8a, 0xbb, 0x1e, 0xf1, 0x1d, 0x71, 0xc6, 0xe7, 0x5f, 0x02,
	0xc3, 0xcb, 0x6b, 0xe5, 0xb1, 0x41, 0xe6, 0x80, 0x11, 0x85, 0xf1, 0x3b, 0xbd, 0x61, 0x36, 0xe8,
	0xa1, 0x08, 0x29, 0x61, 0x00, 0x56, 0x2a, 0x45, 0x18, 0xcf, 0xa9, 0xc6, 0x5c, 0x30, 0xa7, 0x71,
	0x12, 0xcc, 0xa8, 0xce, 0x86, 0xe0, 0xca, 0xcf, 0xe5, 0x2c, 0xf8, 0x4a, 0xa5, 0xa0, 0x06, 0x1b,
	0x80, 0x13, 0x4d, 0xe2, 0xb9, 0x22, 0x53, 0xc9, 0xb1, 0xa4, 0x56, 0x27, 0xbc, 0x45, 0xc9, 0x44,
	0x52, 0xbb, 0x1b, 0x3d, 0x4d, 0x92, 0x88, 0x3a, 0x4a, 0x0d, 0x17, 0xb3, 0x54, 0x4e, 0x16, 0x4b,
	0xea, 0xe6, 0x96, 0xfa, 0xfa, 0x97, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xce, 0x0f, 0xc9,
	0xbe, 0x01, 0x00, 0x00,
}
