// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Primitive {
    #[prost(uint64, tag="1")]
    pub id: u64,
    #[prost(uint64, tag="2")]
    pub subject: u64,
    #[prost(uint64, tag="3")]
    pub predicate: u64,
    #[prost(uint64, tag="4")]
    pub object: u64,
    #[prost(uint64, tag="5")]
    pub label: u64,
    #[prost(uint64, tag="6")]
    pub replaces: u64,
    #[prost(bytes="vec", tag="8")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="9")]
    pub deleted: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PrimitiveType {
    Link = 0,
    Iri = 1,
    String = 2,
    Bnode = 3,
    TypedStr = 4,
    LangStr = 5,
    Int = 6,
    Float = 7,
    Bool = 8,
    Timestamp = 9,
}
impl PrimitiveType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Link => "LINK",
            Self::Iri => "IRI",
            Self::String => "STRING",
            Self::Bnode => "BNODE",
            Self::TypedStr => "TYPED_STR",
            Self::LangStr => "LANG_STR",
            Self::Int => "INT",
            Self::Float => "FLOAT",
            Self::Bool => "BOOL",
            Self::Timestamp => "TIMESTAMP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LINK" => Some(Self::Link),
            "IRI" => Some(Self::Iri),
            "STRING" => Some(Self::String),
            "BNODE" => Some(Self::Bnode),
            "TYPED_STR" => Some(Self::TypedStr),
            "LANG_STR" => Some(Self::LangStr),
            "INT" => Some(Self::Int),
            "FLOAT" => Some(Self::Float),
            "BOOL" => Some(Self::Bool),
            "TIMESTAMP" => Some(Self::Timestamp),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogDelta {
    #[prost(uint64, tag="1")]
    pub id: u64,
    #[prost(message, optional, tag="2")]
    pub quad: ::core::option::Option<super::pquads::Quad>,
    #[prost(int32, tag="3")]
    pub action: i32,
    #[prost(int64, tag="4")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HistoryEntry {
    #[prost(uint64, repeated, tag="1")]
    pub history: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeData {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub size: i64,
    #[prost(message, optional, tag="3")]
    pub value: ::core::option::Option<super::pquads::Value>,
}
// @@protoc_insertion_point(module)
