//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/cayley/graph/proto/primitive.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto_2epb_2eh
#define github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto;
}  // extern "C"
namespace proto {
enum PrimitiveType : int;
extern const uint32_t PrimitiveType_internal_data_[];
class Primitive;
struct PrimitiveDefaultTypeInternal;
extern PrimitiveDefaultTypeInternal _Primitive_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Primitive_class_data_;
}  // namespace proto
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::proto::PrimitiveType_internal_data_>
    internal::EnumTraitsImpl::value<::proto::PrimitiveType>;
}  // namespace protobuf
}  // namespace google

namespace proto {
enum PrimitiveType : int {
  LINK = 0,
  IRI = 1,
  STRING = 2,
  BNODE = 3,
  TYPED_STR = 4,
  LANG_STR = 5,
  INT = 6,
  FLOAT = 7,
  BOOL = 8,
  TIMESTAMP = 9,
  PrimitiveType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  PrimitiveType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t PrimitiveType_internal_data_[];
inline constexpr PrimitiveType PrimitiveType_MIN =
    static_cast<PrimitiveType>(0);
inline constexpr PrimitiveType PrimitiveType_MAX =
    static_cast<PrimitiveType>(9);
inline bool PrimitiveType_IsValid(int value) {
  return 0 <= value && value <= 9;
}
inline constexpr int PrimitiveType_ARRAYSIZE = 9 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PrimitiveType_descriptor();
template <typename T>
const ::std::string& PrimitiveType_Name(T value) {
  static_assert(::std::is_same<T, PrimitiveType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to PrimitiveType_Name().");
  return PrimitiveType_Name(static_cast<PrimitiveType>(value));
}
template <>
inline const ::std::string& PrimitiveType_Name(PrimitiveType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PrimitiveType_descriptor, 0, 9>(
      static_cast<int>(value));
}
inline bool PrimitiveType_Parse(
    ::absl::string_view name, PrimitiveType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<PrimitiveType>(PrimitiveType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Primitive final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.Primitive) */ {
 public:
  inline Primitive() : Primitive(nullptr) {}
  ~Primitive() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Primitive* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Primitive));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Primitive(::google::protobuf::internal::ConstantInitialized);

  inline Primitive(const Primitive& from) : Primitive(nullptr, from) {}
  inline Primitive(Primitive&& from) noexcept
      : Primitive(nullptr, ::std::move(from)) {}
  inline Primitive& operator=(const Primitive& from) {
    CopyFrom(from);
    return *this;
  }
  inline Primitive& operator=(Primitive&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Primitive& default_instance() {
    return *reinterpret_cast<const Primitive*>(
        &_Primitive_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Primitive& a, Primitive& b) { a.Swap(&b); }
  inline void Swap(Primitive* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Primitive* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Primitive* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Primitive>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Primitive& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Primitive& from) { Primitive::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Primitive* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.Primitive"; }

  explicit Primitive(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Primitive(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Primitive& from);
  Primitive(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Primitive&& from) noexcept
      : Primitive(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValueFieldNumber = 8,
    kIDFieldNumber = 1,
    kSubjectFieldNumber = 2,
    kPredicateFieldNumber = 3,
    kObjectFieldNumber = 4,
    kLabelFieldNumber = 5,
    kReplacesFieldNumber = 6,
    kDeletedFieldNumber = 9,
  };
  // bytes Value = 8;
  void clear_value() ;
  const ::std::string& value() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_value(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_value();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_value();
  void set_allocated_value(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_value() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_value(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_value();

  public:
  // uint64 ID = 1;
  void clear_id() ;
  ::uint64_t id() const;
  void set_id(::uint64_t value);

  private:
  ::uint64_t _internal_id() const;
  void _internal_set_id(::uint64_t value);

  public:
  // uint64 Subject = 2;
  void clear_subject() ;
  ::uint64_t subject() const;
  void set_subject(::uint64_t value);

  private:
  ::uint64_t _internal_subject() const;
  void _internal_set_subject(::uint64_t value);

  public:
  // uint64 Predicate = 3;
  void clear_predicate() ;
  ::uint64_t predicate() const;
  void set_predicate(::uint64_t value);

  private:
  ::uint64_t _internal_predicate() const;
  void _internal_set_predicate(::uint64_t value);

  public:
  // uint64 Object = 4;
  void clear_object() ;
  ::uint64_t object() const;
  void set_object(::uint64_t value);

  private:
  ::uint64_t _internal_object() const;
  void _internal_set_object(::uint64_t value);

  public:
  // uint64 Label = 5;
  void clear_label() ;
  ::uint64_t label() const;
  void set_label(::uint64_t value);

  private:
  ::uint64_t _internal_label() const;
  void _internal_set_label(::uint64_t value);

  public:
  // uint64 Replaces = 6;
  void clear_replaces() ;
  ::uint64_t replaces() const;
  void set_replaces(::uint64_t value);

  private:
  ::uint64_t _internal_replaces() const;
  void _internal_set_replaces(::uint64_t value);

  public:
  // bool Deleted = 9;
  void clear_deleted() ;
  bool deleted() const;
  void set_deleted(bool value);

  private:
  bool _internal_deleted() const;
  void _internal_set_deleted(bool value);

  public:
  // @@protoc_insertion_point(class_scope:proto.Primitive)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 8,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Primitive& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr value_;
    ::uint64_t id_;
    ::uint64_t subject_;
    ::uint64_t predicate_;
    ::uint64_t object_;
    ::uint64_t label_;
    ::uint64_t replaces_;
    bool deleted_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Primitive_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Primitive

// uint64 ID = 1;
inline void Primitive::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint64_t Primitive::id() const {
  // @@protoc_insertion_point(field_get:proto.Primitive.ID)
  return _internal_id();
}
inline void Primitive::set_id(::uint64_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:proto.Primitive.ID)
}
inline ::uint64_t Primitive::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void Primitive::_internal_set_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// uint64 Subject = 2;
inline void Primitive::clear_subject() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.subject_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint64_t Primitive::subject() const {
  // @@protoc_insertion_point(field_get:proto.Primitive.Subject)
  return _internal_subject();
}
inline void Primitive::set_subject(::uint64_t value) {
  _internal_set_subject(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:proto.Primitive.Subject)
}
inline ::uint64_t Primitive::_internal_subject() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.subject_;
}
inline void Primitive::_internal_set_subject(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.subject_ = value;
}

// uint64 Predicate = 3;
inline void Primitive::clear_predicate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.predicate_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint64_t Primitive::predicate() const {
  // @@protoc_insertion_point(field_get:proto.Primitive.Predicate)
  return _internal_predicate();
}
inline void Primitive::set_predicate(::uint64_t value) {
  _internal_set_predicate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:proto.Primitive.Predicate)
}
inline ::uint64_t Primitive::_internal_predicate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.predicate_;
}
inline void Primitive::_internal_set_predicate(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.predicate_ = value;
}

// uint64 Object = 4;
inline void Primitive::clear_object() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint64_t Primitive::object() const {
  // @@protoc_insertion_point(field_get:proto.Primitive.Object)
  return _internal_object();
}
inline void Primitive::set_object(::uint64_t value) {
  _internal_set_object(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:proto.Primitive.Object)
}
inline ::uint64_t Primitive::_internal_object() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.object_;
}
inline void Primitive::_internal_set_object(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_ = value;
}

// uint64 Label = 5;
inline void Primitive::clear_label() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.label_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint64_t Primitive::label() const {
  // @@protoc_insertion_point(field_get:proto.Primitive.Label)
  return _internal_label();
}
inline void Primitive::set_label(::uint64_t value) {
  _internal_set_label(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:proto.Primitive.Label)
}
inline ::uint64_t Primitive::_internal_label() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.label_;
}
inline void Primitive::_internal_set_label(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.label_ = value;
}

// uint64 Replaces = 6;
inline void Primitive::clear_replaces() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.replaces_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::uint64_t Primitive::replaces() const {
  // @@protoc_insertion_point(field_get:proto.Primitive.Replaces)
  return _internal_replaces();
}
inline void Primitive::set_replaces(::uint64_t value) {
  _internal_set_replaces(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:proto.Primitive.Replaces)
}
inline ::uint64_t Primitive::_internal_replaces() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.replaces_;
}
inline void Primitive::_internal_set_replaces(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.replaces_ = value;
}

// bytes Value = 8;
inline void Primitive::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Primitive::value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.Primitive.Value)
  return _internal_value();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Primitive::set_value(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.value_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.Primitive.Value)
}
inline ::std::string* PROTOBUF_NONNULL Primitive::mutable_value()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:proto.Primitive.Value)
  return _s;
}
inline const ::std::string& Primitive::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_.Get();
}
inline void Primitive::_internal_set_value(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Primitive::_internal_mutable_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.value_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Primitive::release_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.Primitive.Value)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.value_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.value_.Set("", GetArena());
  }
  return released;
}
inline void Primitive::set_allocated_value(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.value_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.Primitive.Value)
}

// bool Deleted = 9;
inline void Primitive::clear_deleted() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.deleted_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline bool Primitive::deleted() const {
  // @@protoc_insertion_point(field_get:proto.Primitive.Deleted)
  return _internal_deleted();
}
inline void Primitive::set_deleted(bool value) {
  _internal_set_deleted(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:proto.Primitive.Deleted)
}
inline bool Primitive::_internal_deleted() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.deleted_;
}
inline void Primitive::_internal_set_deleted(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.deleted_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::proto::PrimitiveType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::proto::PrimitiveType>() {
  return ::proto::PrimitiveType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fprimitive_2eproto_2epb_2eh
