// Copyright 2015 The Cayley Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/cayley/graph/proto/serializations.proto (package proto, syntax proto3)
/* eslint-disable */

import { Quad, Value } from '../../quad/pquads/quads.pb.js'
import type { MessageType } from '@aptre/protobuf-es-lite/message'
import { createMessageType } from '@aptre/protobuf-es-lite/message'
import { ScalarType } from '@aptre/protobuf-es-lite/scalar'
import type { PartialFieldInfo } from '@aptre/protobuf-es-lite/field'

export const protobufPackage = 'proto'

/**
 * @generated from message proto.LogDelta
 */
export interface LogDelta {
  /**
   * @generated from field: uint64 ID = 1;
   */
  ID?: bigint
  /**
   * @generated from field: pquads.Quad Quad = 2;
   */
  Quad?: Quad
  /**
   * @generated from field: int32 Action = 3;
   */
  Action?: number
  /**
   * @generated from field: int64 Timestamp = 4;
   */
  Timestamp?: bigint
}

export const LogDelta: MessageType<LogDelta> =
  /* @__PURE__ */ createMessageType({
    typeName: 'proto.LogDelta',
    fields: [
      { no: 1, name: 'ID', kind: 'scalar', T: ScalarType.UINT64 },
      { no: 2, name: 'Quad', kind: 'message', T: () => Quad },
      { no: 3, name: 'Action', kind: 'scalar', T: ScalarType.INT32 },
      { no: 4, name: 'Timestamp', kind: 'scalar', T: ScalarType.INT64 },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
  })

/**
 * @generated from message proto.HistoryEntry
 */
export interface HistoryEntry {
  /**
   * @generated from field: repeated uint64 History = 1;
   */
  History?: bigint[]
}

export const HistoryEntry: MessageType<HistoryEntry> =
  /* @__PURE__ */ createMessageType({
    typeName: 'proto.HistoryEntry',
    fields: [
      {
        no: 1,
        name: 'History',
        kind: 'scalar',
        T: ScalarType.UINT64,
        repeated: true,
      },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
  })

/**
 * @generated from message proto.NodeData
 */
export interface NodeData {
  /**
   * @generated from field: string Name = 1;
   */
  Name?: string
  /**
   * @generated from field: int64 Size = 2;
   */
  Size?: bigint
  /**
   * @generated from field: pquads.Value value = 3;
   */
  value?: Value
}

export const NodeData: MessageType<NodeData> =
  /* @__PURE__ */ createMessageType({
    typeName: 'proto.NodeData',
    fields: [
      { no: 1, name: 'Name', kind: 'scalar', T: ScalarType.STRING },
      { no: 2, name: 'Size', kind: 'scalar', T: ScalarType.INT64 },
      { no: 3, name: 'value', kind: 'message', T: () => Value },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
  })
