//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/cayley/graph/proto/serializations.proto
// Protobuf C++ Version: 6.33.4

#include "serializations.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {

inline constexpr HistoryEntry::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        history_{},
        _history_cached_byte_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR HistoryEntry::HistoryEntry(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(HistoryEntry_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HistoryEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HistoryEntryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HistoryEntryDefaultTypeInternal() {}
  union {
    HistoryEntry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HistoryEntryDefaultTypeInternal _HistoryEntry_default_instance_;

inline constexpr NodeData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_{nullptr},
        size_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR NodeData::NodeData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(NodeData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NodeDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NodeDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NodeDataDefaultTypeInternal() {}
  union {
    NodeData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NodeDataDefaultTypeInternal _NodeData_default_instance_;

inline constexpr LogDelta::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        quad_{nullptr},
        id_{::uint64_t{0u}},
        timestamp_{::int64_t{0}},
        action_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LogDelta::LogDelta(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(LogDelta_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LogDeltaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LogDeltaDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LogDeltaDefaultTypeInternal() {}
  union {
    LogDelta _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LogDeltaDefaultTypeInternal _LogDelta_default_instance_;
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto = nullptr;
const ::uint32_t
    TableStruct_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::LogDelta, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::LogDelta, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::proto::LogDelta, _impl_.quad_),
        PROTOBUF_FIELD_OFFSET(::proto::LogDelta, _impl_.action_),
        PROTOBUF_FIELD_OFFSET(::proto::LogDelta, _impl_.timestamp_),
        1,
        0,
        3,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::HistoryEntry, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::HistoryEntry, _impl_.history_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::NodeData, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::NodeData, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::proto::NodeData, _impl_.size_),
        PROTOBUF_FIELD_OFFSET(::proto::NodeData, _impl_.value_),
        0,
        2,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::LogDelta)},
        {11, sizeof(::proto::HistoryEntry)},
        {16, sizeof(::proto::NodeData)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::_LogDelta_default_instance_._instance,
    &::proto::_HistoryEntry_default_instance_._instance,
    &::proto::_NodeData_default_instance_._instance,
};
const char descriptor_table_protodef_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\nCgithub.com/aperturerobotics/cayley/gra"
    "ph/proto/serializations.proto\022\005proto\032:gi"
    "thub.com/aperturerobotics/cayley/quad/pq"
    "uads/quads.proto\"U\n\010LogDelta\022\n\n\002ID\030\001 \001(\004"
    "\022\032\n\004Quad\030\002 \001(\0132\014.pquads.Quad\022\016\n\006Action\030\003"
    " \001(\005\022\021\n\tTimestamp\030\004 \001(\003\"\037\n\014HistoryEntry\022"
    "\017\n\007History\030\001 \003(\004\"D\n\010NodeData\022\014\n\004Name\030\001 \001"
    "(\t\022\014\n\004Size\030\002 \001(\003\022\034\n\005value\030\003 \001(\0132\r.pquads"
    ".ValueB0Z.github.com/aperturerobotics/ca"
    "yley/graph/protob\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto_deps[1] = {
        &::descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fquad_2fpquads_2fquads_2eproto,
};
static ::absl::once_flag descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto = {
    false,
    false,
    384,
    descriptor_table_protodef_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto,
    "github.com/aperturerobotics/cayley/graph/proto/serializations.proto",
    &descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto_once,
    descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto::offsets,
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto,
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto,
};
namespace proto {
// ===================================================================

class LogDelta::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<LogDelta>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(LogDelta, _impl_._has_bits_);
};

void LogDelta::clear_quad() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.quad_ != nullptr) _impl_.quad_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
LogDelta::LogDelta(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LogDelta_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.LogDelta)
}
PROTOBUF_NDEBUG_INLINE LogDelta::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::LogDelta& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

LogDelta::LogDelta(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const LogDelta& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LogDelta_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LogDelta* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.quad_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.quad_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, action_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::action_));

  // @@protoc_insertion_point(copy_constructor:proto.LogDelta)
}
PROTOBUF_NDEBUG_INLINE LogDelta::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void LogDelta::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, quad_),
           0,
           offsetof(Impl_, action_) -
               offsetof(Impl_, quad_) +
               sizeof(Impl_::action_));
}
LogDelta::~LogDelta() {
  // @@protoc_insertion_point(destructor:proto.LogDelta)
  SharedDtor(*this);
}
inline void LogDelta::SharedDtor(MessageLite& self) {
  LogDelta& this_ = static_cast<LogDelta&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.quad_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL LogDelta::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) LogDelta(arena);
}
constexpr auto LogDelta::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(LogDelta),
                                            alignof(LogDelta));
}
constexpr auto LogDelta::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_LogDelta_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &LogDelta::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<LogDelta>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &LogDelta::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<LogDelta>(), &LogDelta::ByteSizeLong,
              &LogDelta::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(LogDelta, _impl_._cached_size_),
          false,
      },
      &LogDelta::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull LogDelta_class_data_ =
        LogDelta::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
LogDelta::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&LogDelta_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(LogDelta_class_data_.tc_table);
  return LogDelta_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2>
LogDelta::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(LogDelta, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    LogDelta_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::LogDelta>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 Timestamp = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LogDelta, _impl_.timestamp_), 2>(),
     {32, 2, 0,
      PROTOBUF_FIELD_OFFSET(LogDelta, _impl_.timestamp_)}},
    // uint64 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LogDelta, _impl_.id_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(LogDelta, _impl_.id_)}},
    // .pquads.Quad Quad = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(LogDelta, _impl_.quad_)}},
    // int32 Action = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LogDelta, _impl_.action_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(LogDelta, _impl_.action_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 ID = 1;
    {PROTOBUF_FIELD_OFFSET(LogDelta, _impl_.id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // .pquads.Quad Quad = 2;
    {PROTOBUF_FIELD_OFFSET(LogDelta, _impl_.quad_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // int32 Action = 3;
    {PROTOBUF_FIELD_OFFSET(LogDelta, _impl_.action_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int64 Timestamp = 4;
    {PROTOBUF_FIELD_OFFSET(LogDelta, _impl_.timestamp_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::pquads::Quad>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void LogDelta::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.LogDelta)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    ABSL_DCHECK(_impl_.quad_ != nullptr);
    _impl_.quad_->Clear();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000eU)) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.action_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.action_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL LogDelta::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const LogDelta& this_ = static_cast<const LogDelta&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL LogDelta::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const LogDelta& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.LogDelta)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint64 ID = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_id(), target);
    }
  }

  // .pquads.Quad Quad = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.quad_, this_._impl_.quad_->GetCachedSize(), target,
        stream);
  }

  // int32 Action = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_action() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_action(), target);
    }
  }

  // int64 Timestamp = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_timestamp() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<4>(
              stream, this_._internal_timestamp(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.LogDelta)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t LogDelta::ByteSizeLong(const MessageLite& base) {
  const LogDelta& this_ = static_cast<const LogDelta&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t LogDelta::ByteSizeLong() const {
  const LogDelta& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.LogDelta)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // .pquads.Quad Quad = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.quad_);
    }
    // uint64 ID = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_id());
      }
    }
    // int64 Timestamp = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_timestamp() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp());
      }
    }
    // int32 Action = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_action() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_action());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void LogDelta::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<LogDelta*>(&to_msg);
  auto& from = static_cast<const LogDelta&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.LogDelta)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.quad_ != nullptr);
      if (_this->_impl_.quad_ == nullptr) {
        _this->_impl_.quad_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.quad_);
      } else {
        _this->_impl_.quad_->MergeFrom(*from._impl_.quad_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_timestamp() != 0) {
        _this->_impl_.timestamp_ = from._impl_.timestamp_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_action() != 0) {
        _this->_impl_.action_ = from._impl_.action_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void LogDelta::CopyFrom(const LogDelta& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.LogDelta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LogDelta::InternalSwap(LogDelta* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LogDelta, _impl_.action_)
      + sizeof(LogDelta::_impl_.action_)
      - PROTOBUF_FIELD_OFFSET(LogDelta, _impl_.quad_)>(
          reinterpret_cast<char*>(&_impl_.quad_),
          reinterpret_cast<char*>(&other->_impl_.quad_));
}

::google::protobuf::Metadata LogDelta::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class HistoryEntry::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<HistoryEntry>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HistoryEntry, _impl_._has_bits_);
};

HistoryEntry::HistoryEntry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HistoryEntry_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.HistoryEntry)
}
PROTOBUF_NDEBUG_INLINE HistoryEntry::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::HistoryEntry& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        history_{visibility, arena, from.history_},
        _history_cached_byte_size_{0} {}

HistoryEntry::HistoryEntry(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const HistoryEntry& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HistoryEntry_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  HistoryEntry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.HistoryEntry)
}
PROTOBUF_NDEBUG_INLINE HistoryEntry::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        history_{visibility, arena},
        _history_cached_byte_size_{0} {}

inline void HistoryEntry::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
HistoryEntry::~HistoryEntry() {
  // @@protoc_insertion_point(destructor:proto.HistoryEntry)
  SharedDtor(*this);
}
inline void HistoryEntry::SharedDtor(MessageLite& self) {
  HistoryEntry& this_ = static_cast<HistoryEntry&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL HistoryEntry::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) HistoryEntry(arena);
}
constexpr auto HistoryEntry::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(HistoryEntry, _impl_.history_) +
          decltype(HistoryEntry::_impl_.history_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(HistoryEntry), alignof(HistoryEntry), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&HistoryEntry::PlacementNew_,
                                 sizeof(HistoryEntry),
                                 alignof(HistoryEntry));
  }
}
constexpr auto HistoryEntry::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_HistoryEntry_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &HistoryEntry::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<HistoryEntry>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &HistoryEntry::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<HistoryEntry>(), &HistoryEntry::ByteSizeLong,
              &HistoryEntry::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(HistoryEntry, _impl_._cached_size_),
          false,
      },
      &HistoryEntry::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull HistoryEntry_class_data_ =
        HistoryEntry::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
HistoryEntry::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&HistoryEntry_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(HistoryEntry_class_data_.tc_table);
  return HistoryEntry_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
HistoryEntry::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HistoryEntry, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    HistoryEntry_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::HistoryEntry>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated uint64 History = 1;
    {::_pbi::TcParser::FastV64P1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(HistoryEntry, _impl_.history_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated uint64 History = 1;
    {PROTOBUF_FIELD_OFFSET(HistoryEntry, _impl_.history_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void HistoryEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.HistoryEntry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.history_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL HistoryEntry::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const HistoryEntry& this_ = static_cast<const HistoryEntry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL HistoryEntry::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const HistoryEntry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.HistoryEntry)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated uint64 History = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    {
      int byte_size = this_._impl_._history_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt64Packed(
            1, this_._internal_history(), byte_size, target);
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.HistoryEntry)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t HistoryEntry::ByteSizeLong(const MessageLite& base) {
  const HistoryEntry& this_ = static_cast<const HistoryEntry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t HistoryEntry::ByteSizeLong() const {
  const HistoryEntry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.HistoryEntry)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated uint64 History = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt64SizeWithPackedTagSize(
              this_._internal_history(), 1,
              this_._impl_._history_cached_byte_size_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void HistoryEntry::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<HistoryEntry*>(&to_msg);
  auto& from = static_cast<const HistoryEntry&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.HistoryEntry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_history()->MergeFrom(from._internal_history());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void HistoryEntry::CopyFrom(const HistoryEntry& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.HistoryEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HistoryEntry::InternalSwap(HistoryEntry* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.history_.InternalSwap(&other->_impl_.history_);
}

::google::protobuf::Metadata HistoryEntry::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NodeData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<NodeData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NodeData, _impl_._has_bits_);
};

void NodeData::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.value_ != nullptr) _impl_.value_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
NodeData::NodeData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NodeData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.NodeData)
}
PROTOBUF_NDEBUG_INLINE NodeData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::NodeData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

NodeData::NodeData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NodeData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NodeData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NodeData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.value_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.value_)
                : nullptr;
  _impl_.size_ = from._impl_.size_;

  // @@protoc_insertion_point(copy_constructor:proto.NodeData)
}
PROTOBUF_NDEBUG_INLINE NodeData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void NodeData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, value_),
           0,
           offsetof(Impl_, size_) -
               offsetof(Impl_, value_) +
               sizeof(Impl_::size_));
}
NodeData::~NodeData() {
  // @@protoc_insertion_point(destructor:proto.NodeData)
  SharedDtor(*this);
}
inline void NodeData::SharedDtor(MessageLite& self) {
  NodeData& this_ = static_cast<NodeData&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  delete this_._impl_.value_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL NodeData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NodeData(arena);
}
constexpr auto NodeData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NodeData),
                                            alignof(NodeData));
}
constexpr auto NodeData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NodeData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &NodeData::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NodeData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NodeData::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NodeData>(), &NodeData::ByteSizeLong,
              &NodeData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NodeData, _impl_._cached_size_),
          false,
      },
      &NodeData::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NodeData_class_data_ =
        NodeData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NodeData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NodeData_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NodeData_class_data_.tc_table);
  return NodeData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 27, 2>
NodeData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NodeData, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    NodeData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::NodeData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string Name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(NodeData, _impl_.name_)}},
    // int64 Size = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(NodeData, _impl_.size_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(NodeData, _impl_.size_)}},
    // .pquads.Value value = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(NodeData, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string Name = 1;
    {PROTOBUF_FIELD_OFFSET(NodeData, _impl_.name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 Size = 2;
    {PROTOBUF_FIELD_OFFSET(NodeData, _impl_.size_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // .pquads.Value value = 3;
    {PROTOBUF_FIELD_OFFSET(NodeData, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::pquads::Value>()},
  }},
  {{
    "\16\4\0\0\0\0\0\0"
    "proto.NodeData"
    "Name"
  }},
};
PROTOBUF_NOINLINE void NodeData::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.NodeData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.value_ != nullptr);
      _impl_.value_->Clear();
    }
  }
  _impl_.size_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NodeData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NodeData& this_ = static_cast<const NodeData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NodeData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NodeData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.NodeData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string Name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.NodeData.Name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int64 Size = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_size() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_size(), target);
    }
  }

  // .pquads.Value value = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.value_, this_._impl_.value_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.NodeData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NodeData::ByteSizeLong(const MessageLite& base) {
  const NodeData& this_ = static_cast<const NodeData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NodeData::ByteSizeLong() const {
  const NodeData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.NodeData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string Name = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
    // .pquads.Value value = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.value_);
    }
    // int64 Size = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_size() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_size());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NodeData::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<NodeData*>(&to_msg);
  auto& from = static_cast<const NodeData&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.NodeData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.value_ != nullptr);
      if (_this->_impl_.value_ == nullptr) {
        _this->_impl_.value_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.value_);
      } else {
        _this->_impl_.value_->MergeFrom(*from._impl_.value_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_size() != 0) {
        _this->_impl_.size_ = from._impl_.size_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void NodeData::CopyFrom(const NodeData& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.NodeData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NodeData::InternalSwap(NodeData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NodeData, _impl_.size_)
      + sizeof(NodeData::_impl_.size_)
      - PROTOBUF_FIELD_OFFSET(NodeData, _impl_.value_)>(
          reinterpret_cast<char*>(&_impl_.value_),
          reinterpret_cast<char*>(&other->_impl_.value_));
}

::google::protobuf::Metadata NodeData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fproto_2fserializations_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
