// @generated
// This file is @generated by prost-build.
/// QuadIndexList stores the configured quad indexes.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuadIndexList {
    /// Indexes are the quad indexes in priority order.
    #[prost(message, repeated, tag="1")]
    pub indexes: ::prost::alloc::vec::Vec<QuadIndexMeta>,
}
/// QuadIndexMeta stores a single quad index definition.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuadIndexMeta {
    /// Dirs are quad.Direction numeric values.
    #[prost(uint32, repeated, tag="1")]
    pub dirs: ::prost::alloc::vec::Vec<u32>,
    /// Unique indicates the index is unique.
    #[prost(bool, tag="2")]
    pub unique: bool,
}
// @@protoc_insertion_point(module)
