//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/cayley/graph/kv/indexing.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto_2epb_2eh
#define github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto;
}  // extern "C"
namespace kv {
class QuadIndexList;
struct QuadIndexListDefaultTypeInternal;
extern QuadIndexListDefaultTypeInternal _QuadIndexList_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull QuadIndexList_class_data_;
class QuadIndexMeta;
struct QuadIndexMetaDefaultTypeInternal;
extern QuadIndexMetaDefaultTypeInternal _QuadIndexMeta_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull QuadIndexMeta_class_data_;
}  // namespace kv
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace kv {

// ===================================================================


// -------------------------------------------------------------------

class QuadIndexMeta final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kv.QuadIndexMeta) */ {
 public:
  inline QuadIndexMeta() : QuadIndexMeta(nullptr) {}
  ~QuadIndexMeta() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(QuadIndexMeta* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(QuadIndexMeta));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR QuadIndexMeta(::google::protobuf::internal::ConstantInitialized);

  inline QuadIndexMeta(const QuadIndexMeta& from) : QuadIndexMeta(nullptr, from) {}
  inline QuadIndexMeta(QuadIndexMeta&& from) noexcept
      : QuadIndexMeta(nullptr, ::std::move(from)) {}
  inline QuadIndexMeta& operator=(const QuadIndexMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline QuadIndexMeta& operator=(QuadIndexMeta&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QuadIndexMeta& default_instance() {
    return *reinterpret_cast<const QuadIndexMeta*>(
        &_QuadIndexMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(QuadIndexMeta& a, QuadIndexMeta& b) { a.Swap(&b); }
  inline void Swap(QuadIndexMeta* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QuadIndexMeta* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QuadIndexMeta* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<QuadIndexMeta>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const QuadIndexMeta& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const QuadIndexMeta& from) { QuadIndexMeta::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(QuadIndexMeta* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kv.QuadIndexMeta"; }

  explicit QuadIndexMeta(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  QuadIndexMeta(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const QuadIndexMeta& from);
  QuadIndexMeta(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, QuadIndexMeta&& from) noexcept
      : QuadIndexMeta(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDirsFieldNumber = 1,
    kUniqueFieldNumber = 2,
  };
  // repeated uint32 dirs = 1;
  int dirs_size() const;
  private:
  int _internal_dirs_size() const;

  public:
  void clear_dirs() ;
  ::uint32_t dirs(int index) const;
  void set_dirs(int index, ::uint32_t value);
  void add_dirs(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& dirs() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_dirs();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_dirs() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_dirs();

  public:
  // bool unique = 2;
  void clear_unique() ;
  bool unique() const;
  void set_unique(bool value);

  private:
  bool _internal_unique() const;
  void _internal_set_unique(bool value);

  public:
  // @@protoc_insertion_point(class_scope:kv.QuadIndexMeta)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const QuadIndexMeta& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::uint32_t> dirs_;
    ::google::protobuf::internal::CachedSize _dirs_cached_byte_size_;
    bool unique_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull QuadIndexMeta_class_data_;
// -------------------------------------------------------------------

class QuadIndexList final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kv.QuadIndexList) */ {
 public:
  inline QuadIndexList() : QuadIndexList(nullptr) {}
  ~QuadIndexList() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(QuadIndexList* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(QuadIndexList));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR QuadIndexList(::google::protobuf::internal::ConstantInitialized);

  inline QuadIndexList(const QuadIndexList& from) : QuadIndexList(nullptr, from) {}
  inline QuadIndexList(QuadIndexList&& from) noexcept
      : QuadIndexList(nullptr, ::std::move(from)) {}
  inline QuadIndexList& operator=(const QuadIndexList& from) {
    CopyFrom(from);
    return *this;
  }
  inline QuadIndexList& operator=(QuadIndexList&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QuadIndexList& default_instance() {
    return *reinterpret_cast<const QuadIndexList*>(
        &_QuadIndexList_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(QuadIndexList& a, QuadIndexList& b) { a.Swap(&b); }
  inline void Swap(QuadIndexList* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QuadIndexList* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QuadIndexList* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<QuadIndexList>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const QuadIndexList& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const QuadIndexList& from) { QuadIndexList::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(QuadIndexList* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kv.QuadIndexList"; }

  explicit QuadIndexList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  QuadIndexList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const QuadIndexList& from);
  QuadIndexList(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, QuadIndexList&& from) noexcept
      : QuadIndexList(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIndexesFieldNumber = 1,
  };
  // repeated .kv.QuadIndexMeta indexes = 1;
  int indexes_size() const;
  private:
  int _internal_indexes_size() const;

  public:
  void clear_indexes() ;
  ::kv::QuadIndexMeta* PROTOBUF_NONNULL mutable_indexes(int index);
  ::google::protobuf::RepeatedPtrField<::kv::QuadIndexMeta>* PROTOBUF_NONNULL mutable_indexes();

  private:
  const ::google::protobuf::RepeatedPtrField<::kv::QuadIndexMeta>& _internal_indexes() const;
  ::google::protobuf::RepeatedPtrField<::kv::QuadIndexMeta>* PROTOBUF_NONNULL _internal_mutable_indexes();
  public:
  const ::kv::QuadIndexMeta& indexes(int index) const;
  ::kv::QuadIndexMeta* PROTOBUF_NONNULL add_indexes();
  const ::google::protobuf::RepeatedPtrField<::kv::QuadIndexMeta>& indexes() const;
  // @@protoc_insertion_point(class_scope:kv.QuadIndexList)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const QuadIndexList& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::kv::QuadIndexMeta > indexes_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull QuadIndexList_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// QuadIndexList

// repeated .kv.QuadIndexMeta indexes = 1;
inline int QuadIndexList::_internal_indexes_size() const {
  return _internal_indexes().size();
}
inline int QuadIndexList::indexes_size() const {
  return _internal_indexes_size();
}
inline void QuadIndexList::clear_indexes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.indexes_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::kv::QuadIndexMeta* PROTOBUF_NONNULL QuadIndexList::mutable_indexes(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:kv.QuadIndexList.indexes)
  return _internal_mutable_indexes()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::kv::QuadIndexMeta>* PROTOBUF_NONNULL QuadIndexList::mutable_indexes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:kv.QuadIndexList.indexes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_indexes();
}
inline const ::kv::QuadIndexMeta& QuadIndexList::indexes(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kv.QuadIndexList.indexes)
  return _internal_indexes().Get(index);
}
inline ::kv::QuadIndexMeta* PROTOBUF_NONNULL QuadIndexList::add_indexes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::kv::QuadIndexMeta* _add =
      _internal_mutable_indexes()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:kv.QuadIndexList.indexes)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::kv::QuadIndexMeta>& QuadIndexList::indexes() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:kv.QuadIndexList.indexes)
  return _internal_indexes();
}
inline const ::google::protobuf::RepeatedPtrField<::kv::QuadIndexMeta>&
QuadIndexList::_internal_indexes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.indexes_;
}
inline ::google::protobuf::RepeatedPtrField<::kv::QuadIndexMeta>* PROTOBUF_NONNULL
QuadIndexList::_internal_mutable_indexes() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.indexes_;
}

// -------------------------------------------------------------------

// QuadIndexMeta

// repeated uint32 dirs = 1;
inline int QuadIndexMeta::_internal_dirs_size() const {
  return _internal_dirs().size();
}
inline int QuadIndexMeta::dirs_size() const {
  return _internal_dirs_size();
}
inline void QuadIndexMeta::clear_dirs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dirs_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t QuadIndexMeta::dirs(int index) const {
  // @@protoc_insertion_point(field_get:kv.QuadIndexMeta.dirs)
  return _internal_dirs().Get(index);
}
inline void QuadIndexMeta::set_dirs(int index, ::uint32_t value) {
  _internal_mutable_dirs()->Set(index, value);
  // @@protoc_insertion_point(field_set:kv.QuadIndexMeta.dirs)
}
inline void QuadIndexMeta::add_dirs(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_dirs()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:kv.QuadIndexMeta.dirs)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& QuadIndexMeta::dirs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:kv.QuadIndexMeta.dirs)
  return _internal_dirs();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL QuadIndexMeta::mutable_dirs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:kv.QuadIndexMeta.dirs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_dirs();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
QuadIndexMeta::_internal_dirs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dirs_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
QuadIndexMeta::_internal_mutable_dirs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.dirs_;
}

// bool unique = 2;
inline void QuadIndexMeta::clear_unique() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unique_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool QuadIndexMeta::unique() const {
  // @@protoc_insertion_point(field_get:kv.QuadIndexMeta.unique)
  return _internal_unique();
}
inline void QuadIndexMeta::set_unique(bool value) {
  _internal_set_unique(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:kv.QuadIndexMeta.unique)
}
inline bool QuadIndexMeta::_internal_unique() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.unique_;
}
inline void QuadIndexMeta::_internal_set_unique(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unique_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace kv


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto_2epb_2eh
