//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/cayley/graph/kv/indexing.proto
// Protobuf C++ Version: 6.33.4

#include "indexing.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace kv {

inline constexpr QuadIndexMeta::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        dirs_{},
        _dirs_cached_byte_size_{0},
        unique_{false} {}

template <typename>
PROTOBUF_CONSTEXPR QuadIndexMeta::QuadIndexMeta(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(QuadIndexMeta_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct QuadIndexMetaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QuadIndexMetaDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~QuadIndexMetaDefaultTypeInternal() {}
  union {
    QuadIndexMeta _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QuadIndexMetaDefaultTypeInternal _QuadIndexMeta_default_instance_;

inline constexpr QuadIndexList::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        indexes_{} {}

template <typename>
PROTOBUF_CONSTEXPR QuadIndexList::QuadIndexList(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(QuadIndexList_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct QuadIndexListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QuadIndexListDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~QuadIndexListDefaultTypeInternal() {}
  union {
    QuadIndexList _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QuadIndexListDefaultTypeInternal _QuadIndexList_default_instance_;
}  // namespace kv
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto = nullptr;
const ::uint32_t
    TableStruct_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::kv::QuadIndexList, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::kv::QuadIndexList, _impl_.indexes_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::kv::QuadIndexMeta, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::kv::QuadIndexMeta, _impl_.dirs_),
        PROTOBUF_FIELD_OFFSET(::kv::QuadIndexMeta, _impl_.unique_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::kv::QuadIndexList)},
        {5, sizeof(::kv::QuadIndexMeta)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::kv::_QuadIndexList_default_instance_._instance,
    &::kv::_QuadIndexMeta_default_instance_._instance,
};
const char descriptor_table_protodef_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n:github.com/aperturerobotics/cayley/gra"
    "ph/kv/indexing.proto\022\002kv\"3\n\rQuadIndexLis"
    "t\022\"\n\007indexes\030\001 \003(\0132\021.kv.QuadIndexMeta\"-\n"
    "\rQuadIndexMeta\022\014\n\004dirs\030\001 \003(\r\022\016\n\006unique\030\002"
    " \001(\010b\006proto3"
};
static ::absl::once_flag descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto = {
    false,
    false,
    172,
    descriptor_table_protodef_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto,
    "github.com/aperturerobotics/cayley/graph/kv/indexing.proto",
    &descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto::offsets,
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto,
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto,
};
namespace kv {
// ===================================================================

class QuadIndexList::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<QuadIndexList>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(QuadIndexList, _impl_._has_bits_);
};

QuadIndexList::QuadIndexList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, QuadIndexList_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kv.QuadIndexList)
}
PROTOBUF_NDEBUG_INLINE QuadIndexList::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::kv::QuadIndexList& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        indexes_{visibility, arena, from.indexes_} {}

QuadIndexList::QuadIndexList(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const QuadIndexList& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, QuadIndexList_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  QuadIndexList* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:kv.QuadIndexList)
}
PROTOBUF_NDEBUG_INLINE QuadIndexList::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        indexes_{visibility, arena} {}

inline void QuadIndexList::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
QuadIndexList::~QuadIndexList() {
  // @@protoc_insertion_point(destructor:kv.QuadIndexList)
  SharedDtor(*this);
}
inline void QuadIndexList::SharedDtor(MessageLite& self) {
  QuadIndexList& this_ = static_cast<QuadIndexList&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL QuadIndexList::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) QuadIndexList(arena);
}
constexpr auto QuadIndexList::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(QuadIndexList, _impl_.indexes_) +
          decltype(QuadIndexList::_impl_.indexes_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(QuadIndexList), alignof(QuadIndexList), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&QuadIndexList::PlacementNew_,
                                 sizeof(QuadIndexList),
                                 alignof(QuadIndexList));
  }
}
constexpr auto QuadIndexList::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_QuadIndexList_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &QuadIndexList::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<QuadIndexList>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &QuadIndexList::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<QuadIndexList>(), &QuadIndexList::ByteSizeLong,
              &QuadIndexList::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(QuadIndexList, _impl_._cached_size_),
          false,
      },
      &QuadIndexList::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull QuadIndexList_class_data_ =
        QuadIndexList::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
QuadIndexList::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&QuadIndexList_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(QuadIndexList_class_data_.tc_table);
  return QuadIndexList_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
QuadIndexList::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(QuadIndexList, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    QuadIndexList_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kv::QuadIndexList>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .kv.QuadIndexMeta indexes = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(QuadIndexList, _impl_.indexes_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .kv.QuadIndexMeta indexes = 1;
    {PROTOBUF_FIELD_OFFSET(QuadIndexList, _impl_.indexes_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::kv::QuadIndexMeta>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void QuadIndexList::Clear() {
// @@protoc_insertion_point(message_clear_start:kv.QuadIndexList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.indexes_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL QuadIndexList::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const QuadIndexList& this_ = static_cast<const QuadIndexList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL QuadIndexList::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const QuadIndexList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:kv.QuadIndexList)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .kv.QuadIndexMeta indexes = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_indexes_size());
         i < n; i++) {
      const auto& repfield = this_._internal_indexes().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kv.QuadIndexList)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t QuadIndexList::ByteSizeLong(const MessageLite& base) {
  const QuadIndexList& this_ = static_cast<const QuadIndexList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t QuadIndexList::ByteSizeLong() const {
  const QuadIndexList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:kv.QuadIndexList)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .kv.QuadIndexMeta indexes = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_indexes_size();
      for (const auto& msg : this_._internal_indexes()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void QuadIndexList::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<QuadIndexList*>(&to_msg);
  auto& from = static_cast<const QuadIndexList&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:kv.QuadIndexList)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_indexes()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_indexes());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void QuadIndexList::CopyFrom(const QuadIndexList& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:kv.QuadIndexList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void QuadIndexList::InternalSwap(QuadIndexList* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.indexes_.InternalSwap(&other->_impl_.indexes_);
}

::google::protobuf::Metadata QuadIndexList::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class QuadIndexMeta::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<QuadIndexMeta>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(QuadIndexMeta, _impl_._has_bits_);
};

QuadIndexMeta::QuadIndexMeta(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, QuadIndexMeta_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kv.QuadIndexMeta)
}
PROTOBUF_NDEBUG_INLINE QuadIndexMeta::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::kv::QuadIndexMeta& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        dirs_{visibility, arena, from.dirs_},
        _dirs_cached_byte_size_{0} {}

QuadIndexMeta::QuadIndexMeta(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const QuadIndexMeta& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, QuadIndexMeta_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  QuadIndexMeta* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.unique_ = from._impl_.unique_;

  // @@protoc_insertion_point(copy_constructor:kv.QuadIndexMeta)
}
PROTOBUF_NDEBUG_INLINE QuadIndexMeta::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        dirs_{visibility, arena},
        _dirs_cached_byte_size_{0} {}

inline void QuadIndexMeta::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.unique_ = {};
}
QuadIndexMeta::~QuadIndexMeta() {
  // @@protoc_insertion_point(destructor:kv.QuadIndexMeta)
  SharedDtor(*this);
}
inline void QuadIndexMeta::SharedDtor(MessageLite& self) {
  QuadIndexMeta& this_ = static_cast<QuadIndexMeta&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL QuadIndexMeta::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) QuadIndexMeta(arena);
}
constexpr auto QuadIndexMeta::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(QuadIndexMeta, _impl_.dirs_) +
          decltype(QuadIndexMeta::_impl_.dirs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(QuadIndexMeta), alignof(QuadIndexMeta), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&QuadIndexMeta::PlacementNew_,
                                 sizeof(QuadIndexMeta),
                                 alignof(QuadIndexMeta));
  }
}
constexpr auto QuadIndexMeta::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_QuadIndexMeta_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &QuadIndexMeta::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<QuadIndexMeta>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &QuadIndexMeta::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<QuadIndexMeta>(), &QuadIndexMeta::ByteSizeLong,
              &QuadIndexMeta::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(QuadIndexMeta, _impl_._cached_size_),
          false,
      },
      &QuadIndexMeta::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull QuadIndexMeta_class_data_ =
        QuadIndexMeta::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
QuadIndexMeta::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&QuadIndexMeta_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(QuadIndexMeta_class_data_.tc_table);
  return QuadIndexMeta_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
QuadIndexMeta::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(QuadIndexMeta, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    QuadIndexMeta_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kv::QuadIndexMeta>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool unique = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(QuadIndexMeta, _impl_.unique_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(QuadIndexMeta, _impl_.unique_)}},
    // repeated uint32 dirs = 1;
    {::_pbi::TcParser::FastV32P1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(QuadIndexMeta, _impl_.dirs_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated uint32 dirs = 1;
    {PROTOBUF_FIELD_OFFSET(QuadIndexMeta, _impl_.dirs_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
    // bool unique = 2;
    {PROTOBUF_FIELD_OFFSET(QuadIndexMeta, _impl_.unique_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void QuadIndexMeta::Clear() {
// @@protoc_insertion_point(message_clear_start:kv.QuadIndexMeta)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.dirs_.Clear();
  }
  _impl_.unique_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL QuadIndexMeta::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const QuadIndexMeta& this_ = static_cast<const QuadIndexMeta&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL QuadIndexMeta::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const QuadIndexMeta& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:kv.QuadIndexMeta)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated uint32 dirs = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    {
      int byte_size = this_._impl_._dirs_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt32Packed(
            1, this_._internal_dirs(), byte_size, target);
      }
    }
  }

  // bool unique = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_unique() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          2, this_._internal_unique(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kv.QuadIndexMeta)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t QuadIndexMeta::ByteSizeLong(const MessageLite& base) {
  const QuadIndexMeta& this_ = static_cast<const QuadIndexMeta&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t QuadIndexMeta::ByteSizeLong() const {
  const QuadIndexMeta& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:kv.QuadIndexMeta)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated uint32 dirs = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_dirs(), 1,
              this_._impl_._dirs_cached_byte_size_);
    }
    // bool unique = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_unique() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void QuadIndexMeta::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<QuadIndexMeta*>(&to_msg);
  auto& from = static_cast<const QuadIndexMeta&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:kv.QuadIndexMeta)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_dirs()->MergeFrom(from._internal_dirs());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_unique() != 0) {
        _this->_impl_.unique_ = from._impl_.unique_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void QuadIndexMeta::CopyFrom(const QuadIndexMeta& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:kv.QuadIndexMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void QuadIndexMeta::InternalSwap(QuadIndexMeta* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.dirs_.InternalSwap(&other->_impl_.dirs_);
  swap(_impl_.unique_, other->_impl_.unique_);
}

::google::protobuf::Metadata QuadIndexMeta::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace kv
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2fcayley_2fgraph_2fkv_2findexing_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
