// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/cayley/graph/kv/indexing.proto (package kv, syntax proto3)
/* eslint-disable */

import type { MessageType } from '@aptre/protobuf-es-lite/message'
import { createMessageType } from '@aptre/protobuf-es-lite/message'
import { ScalarType } from '@aptre/protobuf-es-lite/scalar'
import type { PartialFieldInfo } from '@aptre/protobuf-es-lite/field'

export const protobufPackage = 'kv'

/**
 * QuadIndexMeta stores a single quad index definition.
 *
 * @generated from message kv.QuadIndexMeta
 */
export interface QuadIndexMeta {
  /**
   * Dirs are quad.Direction numeric values.
   *
   * @generated from field: repeated uint32 dirs = 1;
   */
  dirs?: number[]
  /**
   * Unique indicates the index is unique.
   *
   * @generated from field: bool unique = 2;
   */
  unique?: boolean
}

export const QuadIndexMeta: MessageType<QuadIndexMeta> =
  /* @__PURE__ */ createMessageType({
    typeName: 'kv.QuadIndexMeta',
    fields: [
      {
        no: 1,
        name: 'dirs',
        kind: 'scalar',
        T: ScalarType.UINT32,
        repeated: true,
      },
      { no: 2, name: 'unique', kind: 'scalar', T: ScalarType.BOOL },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
  })

/**
 * QuadIndexList stores the configured quad indexes.
 *
 * @generated from message kv.QuadIndexList
 */
export interface QuadIndexList {
  /**
   * Indexes are the quad indexes in priority order.
   *
   * @generated from field: repeated kv.QuadIndexMeta indexes = 1;
   */
  indexes?: QuadIndexMeta[]
}

export const QuadIndexList: MessageType<QuadIndexList> =
  /* @__PURE__ */ createMessageType({
    typeName: 'kv.QuadIndexList',
    fields: [
      {
        no: 1,
        name: 'indexes',
        kind: 'message',
        T: () => QuadIndexMeta,
        repeated: true,
      },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
  })
