// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.12.2
// source: github.com/aperturerobotics/cayley/graph/kv/indexing.proto

package kv

import (
	fmt "fmt"
	io "io"
	slices "slices"
	strconv "strconv"
	strings "strings"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
)

// QuadIndexList stores the configured quad indexes.
type QuadIndexList struct {
	unknownFields []byte
	// Indexes are the quad indexes in priority order.
	Indexes []*QuadIndexMeta `protobuf:"bytes,1,rep,name=indexes,proto3" json:"indexes,omitempty"`
}

func (x *QuadIndexList) Reset() {
	*x = QuadIndexList{}
}

func (*QuadIndexList) ProtoMessage() {}

func (x *QuadIndexList) GetIndexes() []*QuadIndexMeta {
	if x != nil {
		return x.Indexes
	}
	return nil
}

// QuadIndexMeta stores a single quad index definition.
type QuadIndexMeta struct {
	unknownFields []byte
	// Dirs are quad.Direction numeric values.
	Dirs []uint32 `protobuf:"varint,1,rep,packed,name=dirs,proto3" json:"dirs,omitempty"`
	// Unique indicates the index is unique.
	Unique bool `protobuf:"varint,2,opt,name=unique,proto3" json:"unique,omitempty"`
}

func (x *QuadIndexMeta) Reset() {
	*x = QuadIndexMeta{}
}

func (*QuadIndexMeta) ProtoMessage() {}

func (x *QuadIndexMeta) GetDirs() []uint32 {
	if x != nil {
		return x.Dirs
	}
	return nil
}

func (x *QuadIndexMeta) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (m *QuadIndexList) CloneVT() *QuadIndexList {
	if m == nil {
		return (*QuadIndexList)(nil)
	}
	r := new(QuadIndexList)
	if rhs := m.Indexes; rhs != nil {
		r.Indexes = make([]*QuadIndexMeta, len(rhs))
		for k, v := range rhs {
			r.Indexes[k] = v.CloneVT()
		}
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *QuadIndexList) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *QuadIndexMeta) CloneVT() *QuadIndexMeta {
	if m == nil {
		return (*QuadIndexMeta)(nil)
	}
	r := new(QuadIndexMeta)
	r.Unique = m.Unique
	if rhs := m.Dirs; rhs != nil {
		r.Dirs = slices.Clone(rhs)
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *QuadIndexMeta) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *QuadIndexList) EqualVT(that *QuadIndexList) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Indexes) != len(that.Indexes) {
		return false
	}
	for i, vx := range this.Indexes {
		vy := that.Indexes[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &QuadIndexMeta{}
			}
			if q == nil {
				q = &QuadIndexMeta{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *QuadIndexList) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*QuadIndexList)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *QuadIndexMeta) EqualVT(that *QuadIndexMeta) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Dirs) != len(that.Dirs) {
		return false
	}
	for i, vx := range this.Dirs {
		vy := that.Dirs[i]
		if vx != vy {
			return false
		}
	}
	if this.Unique != that.Unique {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *QuadIndexMeta) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*QuadIndexMeta)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the QuadIndexList message to JSON.
func (x *QuadIndexList) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.Indexes) > 0 || s.HasField("indexes") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("indexes")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Indexes {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("indexes"))
		}
		s.WriteArrayEnd()
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the QuadIndexList to JSON.
func (x *QuadIndexList) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the QuadIndexList message from JSON.
func (x *QuadIndexList) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "indexes":
			s.AddField("indexes")
			if s.ReadNil() {
				x.Indexes = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Indexes = append(x.Indexes, nil)
					return
				}
				v := &QuadIndexMeta{}
				v.UnmarshalProtoJSON(s.WithField("indexes", false))
				if s.Err() != nil {
					return
				}
				x.Indexes = append(x.Indexes, v)
			})
		}
	})
}

// UnmarshalJSON unmarshals the QuadIndexList from JSON.
func (x *QuadIndexList) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the QuadIndexMeta message to JSON.
func (x *QuadIndexMeta) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.Dirs) > 0 || s.HasField("dirs") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("dirs")
		s.WriteUint32Array(x.Dirs)
	}
	if x.Unique || s.HasField("unique") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("unique")
		s.WriteBool(x.Unique)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the QuadIndexMeta to JSON.
func (x *QuadIndexMeta) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the QuadIndexMeta message from JSON.
func (x *QuadIndexMeta) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "dirs":
			s.AddField("dirs")
			if s.ReadNil() {
				x.Dirs = nil
				return
			}
			x.Dirs = s.ReadUint32Array()
		case "unique":
			s.AddField("unique")
			x.Unique = s.ReadBool()
		}
	})
}

// UnmarshalJSON unmarshals the QuadIndexMeta from JSON.
func (x *QuadIndexMeta) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *QuadIndexList) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuadIndexList) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *QuadIndexList) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.Indexes) > 0 {
		for iNdEx := len(m.Indexes) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.Indexes[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QuadIndexMeta) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuadIndexMeta) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *QuadIndexMeta) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Unique {
		i--
		if m.Unique {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Dirs) > 0 {
		var pksize2 int
		for _, num := range m.Dirs {
			pksize2 += protobuf_go_lite.SizeOfVarint(uint64(num))
		}
		i -= pksize2
		j1 := i
		for _, num := range m.Dirs {
			for num >= 1<<7 {
				dAtA[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA[j1] = uint8(num)
			j1++
		}
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(pksize2))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuadIndexList) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Indexes) > 0 {
		for _, e := range m.Indexes {
			l = e.SizeVT()
			n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
		}
	}
	n += len(m.unknownFields)
	return n
}

func (m *QuadIndexMeta) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Dirs) > 0 {
		l = 0
		for _, e := range m.Dirs {
			l += protobuf_go_lite.SizeOfVarint(uint64(e))
		}
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(l)) + l
	}
	if m.Unique {
		n += 2
	}
	n += len(m.unknownFields)
	return n
}

func (x *QuadIndexList) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("QuadIndexList {")
	if len(x.Indexes) > 0 {
		if sb.Len() > 15 {
			sb.WriteString(" ")
		}
		sb.WriteString("indexes: [")
		for i, v := range x.Indexes {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(v.MarshalProtoText())
		}
		sb.WriteString("]")
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *QuadIndexList) String() string {
	return x.MarshalProtoText()
}

func (x *QuadIndexMeta) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("QuadIndexMeta {")
	if len(x.Dirs) > 0 {
		if sb.Len() > 15 {
			sb.WriteString(" ")
		}
		sb.WriteString("dirs: [")
		for i, v := range x.Dirs {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(strconv.FormatUint(uint64(v), 10))
		}
		sb.WriteString("]")
	}
	if x.Unique != false {
		if sb.Len() > 15 {
			sb.WriteString(" ")
		}
		sb.WriteString("unique: ")
		sb.WriteString(strconv.FormatBool(x.Unique))
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *QuadIndexMeta) String() string {
	return x.MarshalProtoText()
}

func (m *QuadIndexList) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuadIndexList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuadIndexList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Indexes", wireType)
			}
			var msglen int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			msglen = int(_v)
			if err != nil {
				return err
			}
			if msglen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Indexes = append(m.Indexes, &QuadIndexMeta{})
			if err := m.Indexes[len(m.Indexes)-1].UnmarshalVT(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *QuadIndexMeta) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuadIndexMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuadIndexMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint32
				v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
				if err != nil {
					return err
				}
				m.Dirs = append(m.Dirs, v)
			} else if wireType == 2 {
				var packedLen int
				var _v uint64
				_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
				packedLen = int(_v)
				if err != nil {
					return err
				}
				if packedLen < 0 {
					return protobuf_go_lite.ErrInvalidLength
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return protobuf_go_lite.ErrInvalidLength
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Dirs) == 0 {
					m.Dirs = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
					if err != nil {
						return err
					}
					m.Dirs = append(m.Dirs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Dirs", wireType)
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unique", wireType)
			}
			var v int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			v = int(_v)
			if err != nil {
				return err
			}
			m.Unique = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
