// @generated
// This file is @generated by prost-build.
/// TestMsg is a test message used for unit tests.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TestMsg {
    #[prost(int32, tag="1")]
    pub value: i32,
}
// @@protoc_insertion_point(module)
